name: Run Scraper from HF

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Taaki aap manually bhi click karke run kar sakein
  schedule:
    - cron: '0 * * * *' # Har ghante run hoga

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Workflow Repo
        uses: actions/checkout@v3

      - name: Install dependencies & Clone Code
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. HF Space clone karein
          git clone https://huggingface.co/spaces/Sudarshan143/Scrapper2 temp_code
          
          # 2. Dependencies install karein
          pip install -r temp_code/requirements\ \(5\).txt
          
          # 3. Playwright browsers install karein
          playwright install chromium
          playwright install-deps

      - name: Run Scraper
        env:
          # Yahan apne secrets wapas set karne honge kyunki code private repo se chal raha hai
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          python temp_code/auto_scraper\ \(1\).py
          
