name: Run Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Force Google DNS Resolver
        run: |
          sudo echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
          sudo echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf > /dev/null

      - name: Install System FFMPEG Core
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg curl git

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone Code Securely (Avoid 429)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Added --depth 1 to pull only the latest state (Super Light Weight)
          git clone --depth 1 https://Sudarshan143:$HF_TOKEN@huggingface.co/spaces/Sudarshan143/Scrapper2 repo_code
          
      - name: Install Dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r repo_code/requirements.txt
          python -m playwright install chromium
          python -m playwright install-deps

      - name: Run Scraper Engine
        timeout-minutes: 20
        working-directory: ./repo_code
        run: |
          python auto_scraper.py

      - name: Auto Save Tracking Progress
        if: always()
        working-directory: ./repo_code
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.name "GitHub Action Engine"
          git config --global user.email "actions@github.com"
          
          git pull origin main || true
          
          if [ -f "posted_movies.txt" ] || [ -f "page_tracker.txt" ]; then
            git add posted_movies.txt page_tracker.txt
            git commit -m "🤖 Sync Engine: Updated database progress [Skip CI]" || exit 0
            git push https://Sudarshan143:$HF_TOKEN@huggingface.co/spaces/Sudarshan143/Scrapper2 main
          fi
          
